---
title: "git_01"
author: "Alex Bell"
date: "Spring Semester 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->


`Twas brillig, and the slithy toves.  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
"Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->


A neighbor of mine in the village.  
Likes to tell how one spring.  
When she was a girl on the farm, she did.  
A childlike thing.  
One day she asked her father.  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->


"The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make.  
The billows smooth and bright —  
And this was odd, because it was.   
 The middle of the night.
  
  The moon was shining sulkily,  
      Because she thought the sun.   
Had got no business to be there.   
      After the day was done —    
        
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->


“I cannot go to school today,”  
Said little Peggy Ann McKay.  
“I have the measles and the mumps,  
A gash, a rash and purple bumps.  
My mouth is wet, my throat is dry,  
I’m going blind in my right eye.  
My tonsils are as big as rocks,  
I’ve counted sixteen chicken pox.  
And there’s one more–that’s seventeen,  
And don’t you think my face looks green?  
My leg is cut–my eyes are blue–  
It might be instamatic flu.  
I cough and sneeze and gasp and choke,  
I’m sure that my left leg is broke–  
My hip hurts when I move my chin,  
My belly button’s caving in,  
My back is wrenched, my ankle’s sprained,  
My ‘pendix pains each time it rains.  
My nose is cold, my toes are numb.  
I have a sliver in my thumb.  